locations:
  - INFORMATION_DESK
  - SCIENCE_SECTION
  - NOVEL_SECTION
  - CHECKOUT_AREA

INFORMATION_DESK:
  goal:
    x: -1.663
    y: -4.861
    yaw: 0.67
  qr_expected: "LOCATION=INFORMATION_DESK"
  timeout: 90
  qr_retries: 2

SCIENCE_SECTION:
  goal:
    x: 0.008
    y: -0.087
    yaw: 0.33
  qr_expected: "LOCATION=SCIENCE_SECTION"
  timeout: 90
  qr_retries: 2

NOVEL_SECTION:
  goal:
    x: 5.541
    y: -1.210
    yaw: 0.0
  qr_expected: "LOCATION=NOVEL_SECTION"
  timeout: 90
  qr_retries: 2

CHECKOUT_AREA:
  goal:
    x: 3.206
    y: -6.159
    yaw: -1.99
  qr_expected: "LOCATION=CHECKOUT_AREA"
  timeout: 90
  qr_retries: 2
